name: Magento2 Upgrade Patch Helper

on:
  pull_request:
    types: [labeled]

jobs:
  magento2-upgrade-patch-helper:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:

      - name: Remove RunUpgradePatchHelper Label
        if: github.event.label.name == 'RunUpgradePatchHelper'
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.removeLabel({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              name: 'RunUpgradePatchHelper'
            });

      - name: Checkout repository
        if: github.event.label.name == 'RunUpgradePatchHelper'
        uses: actions/checkout@v4

#      - name: Generate auth.json, uncomment and configure when needed
#        if: env.SHOULD_RUN_UPGRADE_HELPER == 'yes'
#        env:
#          USERNAME: ${{ secrets.PACKAGIST_USERNAME }}
#          PASSWORD: ${{ secrets.PACKAGIST_PASSWORD }}
#        run: |
#          printf '{\n    "http-basic": {\n        "repo.packagist.com": {\n            "username": "${USERNAME}",\n            "password": "${PASSWORD}"\n        }\n    }\n}' > auth.json

      - name: Run magento2 upgrade patch helper
        if: github.event.label.name == 'RunUpgradePatchHelper'
        uses: convenient/magento2-upgrade-patch-helper-github-action@wip-action
        with:
          working-dir: 'some_subdir'
          vendor-filter: 'foobar|baz'
